name: gateease_employee_app_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_messaging: ^15.2.3
  socket_io_client: ^3.0.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  equatable: ^2.0.7
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.0+3
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600